//! Exports or checks the small metadata-only frontend contract.
use latch_core::{
    AppStatus, VaultAvailability,
    project::{DirectorySelection, ProjectPage, ProjectSummary},
    protocol::Environment,
};
use std::{fs, path::PathBuf};
use ts_rs::TS;

fn main() {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../apps/desktop/src/generated/core.ts");
    let config = ts_rs::Config::default();
    let content = "// Generated by pnpm bindings. Do not edit.\n".to_owned()
        + &[
            VaultAvailability::decl(&config),
            AppStatus::decl(&config),
            Environment::decl(&config),
            ProjectSummary::decl(&config),
            ProjectPage::decl(&config),
            DirectorySelection::decl(&config),
        ]
        .iter()
        .map(|decl| format!("export {decl}\n"))
        .collect::<String>();
    let content = content
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
        + "\n";
    if std::env::args().any(|arg| arg == "--check") {
        if fs::read_to_string(path).ok().as_deref() != Some(content.as_str()) {
            eprintln!("Generated types are stale. Run pnpm bindings.");
            std::process::exit(1);
        }
    } else {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, content).unwrap();
    }
}
